### ISSUE TITLE
Animacion de imagenes en index tapa menu de navegacion

### ISSUE THREAD

**Issue by jopacak** [erwinzam/club_de_las_recetas_web_page#1]
Al hacer hover con el mouse sobre las imagenes que estan en la seccion principal de index.html, la imagen "animada" se coloca en primer plano y tapa el menu de navegacion. Estuve investigando y una posible solución sería agregar en CSS lo siguiente a .navegador:

**z-index: 100;**

Y con eso nunca se vienen al primer plano.
No lo quise cambiar yo para no hacer lío de versiones.
Abrazo.

![image](https://github.com/erwinzam/club_de_las_recetas_web_page/assets/129784739/3aec477b-417d-4135-be5e-563262414ab6)

**Comment by erwinzam** [comment]
Gracias por tomarte el tiempo en buscar la solución a eso. Ya con lo me dijiste del z-index tengo un código de Ariel que trabaja con eso.💪
