### ISSUE TITLE
Carpeta de imagenes

### ISSUE THREAD

**Issue by jopacak** [erwinzam/club_de_las_recetas_web_page#2]
Deberiamos estandarizar y colocar todas las imagenes en la misma carpeta, sea "img" (lo que usé para el grid) o "img\recetas" (lo que se usó para el index), para que no haya dos lugares distintos?

**Comment by erwinzam** [comment]
Si querés mete tus imágenes en esa carpeta, no tengo drama. Igual hay un backup por si las moscas.

PD: no sabía que se podía comentar de códigos en GitHub, yo lo estoy haciendo desde la aplicación de Android. Muy buen aporte Juan 👏👏👏👏👏

**Comment by jopacak** [comment]
Finalizado, moví las imagenes a img\recetas.
